### ISSUE TITLE
metadata.ruleName contains wrong value

### ISSUE THREAD

**Issue by karfau** [kwonoj/tslint-no-unused-expression-chai#17]
With my last contribution to this repository [I added the `public static metadata` to the rule, by spreading](https://github.com/kwonoj/tslint-no-unused-expression-chai/commit/1618b7bcbae55b63631d43e1efa90301d3cb02a3#diff-4f1b55920b9864c8d49c8dffa7103895R113) in the [metadata from tslint's `no-unused-expression`](https://github.com/palantir/tslint/blob/master/src/rules/noUnusedExpressionRule.ts#L38-L65) (this points to the master version, but it will of course spread in the metadata from whatever tslint version is currently installed).

By doing so the field `ruleName` contains the value `no-unused-expression` but it should contain `no-unused-expression-chai`.

As far as I could see, `metadata.ruleName` [is not critical for whether the rule will be picked by tslint](https://github.com/palantir/tslint/search?q=metadata.ruleName&unscoped_q=metadata.ruleName) (tslint derives the rule name from the file name) but I'm not sure if reporting might pick up the field from `metadata` when it is available.

(I discovered this while working on the tool https://github.com/karfau/tslint-report that makes use of `metadata`.)

I see two options for a solution:
a) Fix the `ruleName` by overriding them after spreading:
```
public static metadata = {...BaseUnusedExpressionRule.metadata, ...TSLINT_META, ruleName: 'no-unused-expression-chai'};
```

b) Get rid of future surprises: Copy the (rest of the) metadata from the original rule into `noUnusedExpressionhaiRule.ts`, adopt `ruleName`, own any future changes.

Sorry for introducing the problem, if you prefer I provide a fix in a PR please let me now, how you want it to be fixed (there might be more options then the ones I mentioned).

**Comment by kwonoj** [comment]
I feel a) would be more simplified, duplicating set from tslint to here could make things harder when tslint keep changes.
