### ISSUE TITLE
Support `chai.expect`

### ISSUE THREAD

**Issue by Fjandin** [kwonoj/tslint-no-unused-expression-chai#21]
Any change this could support this use case
```
import * as chai from 'chai'
...
chai.expect(true).to.be.true
...
```

Seems i'm forced to use `expect(true).to.be.true`

**Comment by kwonoj** [comment]
Technically this would be possible but I am currently all tied with other works and this is usecase I don't utilize myself, bit hard to promise anything if I can make changes. If you have PR, I can check those in quickly.

**Comment by kwonoj** [comment]
Closing as deprecated https://github.com/kwonoj/tslint-no-unused-expression-chai/pull/22 .
